---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k0smotron.k0sproject.io
  resources:
  - k0smotronclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k0smotron.k0sproject.io
  resources:
  - k0smotronclusters/finalizers
  verbs:
  - update
- apiGroups:
  - k0smotron.k0sproject.io
  resources:
  - k0smotronclusters/status
  verbs:
  - get
  - patch
  - update
