apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: sample
    app.kubernetes.io/part-of: k0smotron
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k0smotron
  name: sample
spec:
