name: Go build

on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'config/**'
      - '**.md'
      - LICENSE
      - '**.svg'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'config/**'
      - '**.md'
      - LICENSE
      - '**.svg'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for `git describe`
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'

      - name: Build
        run: |
          make build

      - name: Build image
        run: |
          make docker-build

  unittest:
    name: Unit test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          make test
