name: Release

on:
  push:
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.branch_name.outputs.TAG_NAME }}
      image_tag: ${{ steps.image_tag.outputs.IMAGE_TAGS }}
    steps:
      # Ugly hack to get the tag name
      # github.ref gives the full reference like refs.tags.v0.0.1-beta1
      - name: Branch name
        id: branch_name
        run: |
          echo TAG_NAME="${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Prepare image tags
        id: image_tag
        env:
          TAGS: ${{ steps.branch_name.outputs.TAG_NAME }}
        # Basically just replace the '+' with '-' as '+' is not allowed in tags
        run: |
          echo IMAGE_TAGS="${TAGS//+/-}" >> $GITHUB_OUTPUT
  build-image:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run git checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub image registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/k0sproject/k0smotron:${{ needs.release.outputs.image_tag }}
            quay.io/k0sproject/k0smotron:${{ needs.release.outputs.image_tag }}
          push: true

#      - name: Create install.yaml
#        if: github.repository == 'k0sproject/k0smotron'
#        run: |
#          make release IMG=quay.io/k0sproject/k0smotron:${{ needs.release.outputs.image_tag }}
#          mkdir -p release
#          cp install.yaml release/install.yaml
#          git checkout gh-pages
#          git add release/install.yaml && git update-index --refresh
#          git diff-index --quiet HEAD -- || git commit -m "New install.yaml for version ${{ needs.release.outputs.image_tag }}"
#          git push origin gh-pages
